"""initial migration for account table

Revision ID: 60d1844cb5d3
Revises:
Create Date: 2022-12-09 18:25:25.301186

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "60d1844cb5d3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_model(
        "model",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=1024), nullable=True),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("last_active", sa.DateTime(timezone=True), nullable=True),
        
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),

        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),        
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("account")
    # ### end Alembic commands ###
